version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_commits:
  files:
    - README.md

max_jobs: 1

image: Visual Studio 2019

clone_folder: c:\projects\demonssoulsdebug

environment:
  LLVM_PATH: 'C:\Program Files\LLVM'
  VCVARS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat'

install:
  - git submodule update --init --recursive

configuration:
  - Debug

build:
  project: tools\Tools.sln
  parallel: true
  verbosity: minimal

after_build:
  - '"%VCVARS_PATH%" x86'
  - nmake /nologo /f Makefile.mak TARGET=USv100 bin\USv100\debug.elf.patch
  - nmake /nologo /f Makefile.mak TARGET=JPv104 bin\JPv104\debug.elf.patch
  - nmake /nologo /f Makefile.mak TARGET=Asiav104 bin\Asiav104\debug.elf.patch
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug_USv100.zip ./bin/USv100/debug.elf.patch tools/bin/*.exe tools/bin/*.dll ./deploy/USv100/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug_JPv104.zip ./bin/JPv104/debug.elf.patch tools/bin/*.exe tools/bin/*.dll ./deploy/JPv104/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug_Asiav104.zip ./bin/Asiav104/debug.elf.patch tools/bin/*.exe tools/bin/*.dll ./deploy/Asiav104/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
artifacts:
  - path: '*.zip'
