version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_commits:
  files:
    - README.md
    - .github/*
    - .gitattributes

max_jobs: 1

image: Visual Studio 2019

clone_folder: c:\projects\demonssoulsdebug

environment:
  LLVM_PATH: 'C:\Program Files\LLVM'
  VCVARS_PATH: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat'

install:
  - git submodule update --init --recursive
  - nuget restore tools\Tools.sln

configuration:
  - Debug

build:
  project: tools\Tools.sln
  parallel: true
  verbosity: minimal

after_build:
  - '"%VCVARS_PATH%" x86'
  - nmake /nologo /f Makefile.mak TARGET=US_v100 bin\US_v100\debug.elf.patch
  - nmake /nologo /f Makefile.mak TARGET=JP_v104 bin\JP_v104\debug.elf.patch
  - nmake /nologo /f Makefile.mak TARGET=Asia_v104 bin\Asia_v104\debug.elf.patch
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug_US_v100.zip     ./bin/US_v100/debug.elf.patch tools/bin/PatchElf.exe tools/bin/*.dll   ./deploy/US_v100/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug_JP_v104.zip     ./bin/JP_v104/debug.elf.patch tools/bin/PatchElf.exe tools/bin/*.dll   ./deploy/JP_v104/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug_Asia_v104.zip ./bin/Asia_v104/debug.elf.patch tools/bin/PatchElf.exe tools/bin/*.dll ./deploy/Asia_v104/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
artifacts:
  - path: '*.zip'
