version: 1.0.{build}

branches:
  only:
    - master

skip_tags: true
skip_commits:
  files:
    - README.md

max_jobs: 1

image: Visual Studio 2015

clone_folder: c:\projects\demonssoulsdebug

install:
  - git submodule update --init --recursive

configuration:
  - Debug

build:
  project: tools\Tools.sln
  parallel: true
  verbosity: minimal

before_build:
  - clang.exe -target ppc64-unknown-unknown -m64 -mllvm --x86-asm-syntax=intel -c debug_patch.S -o bin\debug_patch.o
  - ld.lld.exe -v --section-start .text=0x10200 bin\debug_patch.o -o bin\debug_patch.elf

after_build:
  - set TZ=GMT
  - git log . > git-log.txt
  - 7z a -r -tzip -mx=9 -x!*/LICENSE.txt DemonsSoulsDebug-%APPVEYOR_BUILD_VERSION%.zip bin/debug_patch.elf tools/bin/*.exe tools/bin/*.dll ./deploy/build.bat ./LICENSE.txt ./deploy/README.txt ./git-log.txt
artifacts:
  - path: '*-*.zip'
